[technote]
id = "RTN-097"
series_id = "RTN"
canonical_url = "https://rtn-097.lsst.io"
github_url = "https://github.com/lsst/rtn-097"
github_default_branch = "main"
date_created = 2025-04-15T20:07:43Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Melissa L."
name.family = "Graham"
internal_id = "grahamml"
orcid = "https://orcid.org/0000-0002-9154-3136"
[[technote.authors.affiliations]]
name = "University of Washington"
internal_id = "Washington"
address = "Dept. of Astronomy, Box 351580, Seattle, WA 98195, USA"
